:toc: left
= Test Lab Guide: OS Version

== Abstract 

This Test Lab Guide (TLG) will provide the user with step-by-step instructions on how to configure a basic network configuration using [OS Version] servers and a [OS Version] client. The resulting test lab environment will provide a stable base for building other test labs. It is recommended that users preserve the start of their test machines once this walk-through has been successfully completed. In a physical environment the hard drive of the machine can be imaged. In a virtual environment, the “snapshot” or equivalent feature can be used to preserve the current state of the operating system. Preserving the working conditions of the basic test lab will allow the user to experiment without fear of having to completely rebuild their environment. The ultimate goal of the TLG is to familiarize the user with the [OS Version] Operating system and how to deploy common network services based on that operating system, and ultimately enable the user to conduct their own experiments in a [OS Version] based environment.

== Introduction 

The purpose of the Test Lab Guides (TLGs) is providing users with practical guidelines for deploying current operating systems in a way that results in a functional configuration. Using a TLG will instruct the user in which servers to create, how to configure the operating systems and services, and how to install and configure additional software. A TLG experience enables the user to experience the entire set-up process from start to finish.  
 
This TLG is written with the goals of reusability and extensibility in mind. The purpose of this particular TLG is to enable the creation of a basic network utilizing [OS Version] as the central operating system. Once this network is complete several other TLGs can be built on top of this base configuration.  
 
Once this lab is completed, it would be wise to save the initial configuration. How this is best done will depend on how the test environment was originally deployed. A physical environment can be preserved by imaging the drives of each machine to be stored in a separate location and retrieved when needed. In a network deployed virtually, a snapshot can be taken of each machine. This will preserve the current settings and configurations. Preserving the lab in a functional state is important, because it allows for a functional configuration to be restored without completely repeating the base lab configuration steps. This is helpful for correcting after a mistake or generating a test environment for a new product.

****
Note: If you are completing these TLG’s in a virtual environment using VMWare and have access to an electronic copy of this document, and you have VMWare Tools installed on the Virtual Machine, utilize the ability to copy and paste text from the host machine to the VM.  Copying and pasting will help to reduce typos and command errors.

* Highlight and right-click a command from this document
* Click Copy
* Right-click in the virtual machine where you would like to copy the text to and click Paste
* If you are working inside a terminal, you may only need to right click in order to copy the command over
****

== Disclaimer

This website contains work created for informational purposes.
Information may be out of date, or changed or updated without notice. By
using this website, you recognize and agree that all information is provided
“AS IS” without warranty of any kind, either express or implied, including,
but not limited to, the implied warranties of merchantability, fitness for a
particular purpose, or non-infringement.

The entire risk arising out of the use of these guides remains with you. IN
NO EVENT SHALL CHAMPLAIN COLLEGE, ITS STUDENTS, FACULTY,
OR ANYONE ELSE INVOLVED IN THE CREATION, PRODUCTION,
OR DELIVERY OF THE GUIDES BE LIABLE TO ANY PERSON FOR
ANY DIRECT, INDIRECT, SPECIAL, OR OTHER CONSEQUENTIAL
DAMAGES FOR ANY USE OF THE MATERIAL ON THIS WEBSITE. This
includes, without limitation, damages for lost profits, business interruption, loss of data or business information, damage to computer equipment or networks, or other loss arising out of the use of any information in the guides.

== Contents of This Guide 

This document contains instructions for setting up the [OS Version] configuration test lab by deploying two servers running [OS], one client running [OS] with a desktop environment, and one firewall built on [OS]. Once completed, the lab will simulate the functioning of a private intranet.  

*Important*: The instructions provided in this document are for educational purposes. They do not represent best practices nor are they recommendations for a production network. These configurations should not be put into place on a production network. This network should be deployed on a separate network specific to testing (physical or virtual). 

=== Network Overview 

The [OS Version] base configuration test lab consists of the following: 

** One server running [OS Version] named fw1
*** IP Address: 192.168.X.X
*** Gateway: N/A
*** DNS Server: 192.168.X.X
*** Hostname: fw1.college.com
*** Two NICs configured to handle traffic between the intranet and the external internet connection 

** One server running [OS Version] named dc1
*** IP Address: 192.168.X.X
*** Gateway: 192.168.X.X
*** DNS Server: 192.168.X.X (localhost)
*** Hostname: dc1.college.com
*** Configured as the intranet Domain Name System (DNS), and Dynamic Host Configuration Protocol (DHCP) server 

** One server running [OS Version] named app1
*** IP Address: 192.168.X.X
*** Gateway: 192.168.X.X
*** DNS Server: 192.168.X.X
*** Hostname: app1.college.com
*** Configured on the intranet as a system logging server 

** One client running [OS Version] named client1 
*** IP Address: 192.168.X.X
*** Gateway: 192.168.X.X
*** DNS Server: 192.168.X.X
*** Hostname: client1.college.com
*** Will have ability to switch between the intranet and internet subnets 

The [OS Version] base configuration TLG is comprised of one subnet: 

** An intranet, known as the internal subnet (192.168.200.0/24 in this example) 

Network Diagram:

[Network Diagram Here]

This document consists of four major parts as follows: 

** Step One - Configure Firewall

** Step Two - Configure Domain Controller

** Step Three - Configure Client

** Step Four - Configure App Server

=== Hardware and Software Requirements 

The following are the minimum required components for deploying the test lab:  

** An installer disc or .iso file for [OS Version], 64 bit

** One machine that will meet the minimum install requirements for [OS] with 2 NICs 

** Three machines that will meet the minimum install requirements for [OS] 
 
=== Using “Sudo”

When running many commands throughout these TLGs you may be required to use ‘sudo’ depending on the level of privilege the current user has.  The ‘sudo’ command allows the command following it to be run at superuser privileges.  It is important to note that the user must be in the ‘sudoers’ file in order to successfully use this command. If you make the account an administrator while installing, it will be added to the ‘sudoers’ file automatically. Once a command is preceded by ‘sudo’ the user will be prompted for the password for the account and then the command can be run at superuser privilege.

== Configuring the Environment
=== **Step One** - Configure Firewall 

The following instructions will detail the installation and configuration of the Firewall system. It will consist of 4 notable sections as follows: 

1. Installing the Operating System
2. Configure TCP/IP Properties
3. Configure NAT Rules
4. Snapshot Configuration

=== Install the Operating System on Firewall

Section Details Here

=== Configure TCP/IP Properties

Section Details Here

=== Configure NAT Rules

Section Details Here

=== Snapshot the Configuration 

Preserving a functional state of the machine is important in case changes are made accidently. This can be done using VMWare’s snapshot functionality or other software packages for hardware labs.

== **Step Two** - Configure Domain Controller 

The following instructions will detail the installation and configuration of the Domain Controller system. It will consist of 6 notable sections as follows: 

1. Installing the Operating System
2. Configure TCP/IP Properties
3. Configure DNS
4. Configure DHCP
5. Reconfigure TCP/IP Properties
6. Rnapshot Configuration

=== Install the Operating System on Domain Controller

Section Details Here

=== Configure TCP/IP Properties

Section Details Here

=== Configure DNS

.Section Details Here

=== Configure DHCP

Section Details Here

=== Reconfigure TCP/IP Properties

Section Details Here

=== Snapshot the Configuration 

Preserving a functional state of the machine is important in case changes are made accidently. This can be done using VMWare’s snapshot functionality or other software packages for hardware labs.

== **Step Three** - Configure Client 

The following instructions will detail the installation and configuration of the Client system. It will consist of 3 notable sections as follows: 

1. Installing the Operating System on Client
2. Configure TCP/IP Properties
3. Snapshot Configuration

=== Install the Operating System

Section Details Here

=== Configure TCP/IP Properties

.Section Details Here

=== Snapshot the Configuration 

Preserving a functional state of the machine is important in case changes are made accidently. This can be done using VMWare’s snapshot functionality or other software packages for hardware labs.

== **Step Four** - Configure App Server

The following instructions will detail the installation and configuration of the App Server system. It will consist of 4 notable sections as follows: 

1. Installing the Operating System on App Server
2. Configure TCP/IP Properties
3. Configure Apache
4. Snapshot Configuration

=== Install the Operating System

Section Details Here

=== Configure TCP/IP Properties

Section Details Here

=== Configuring Apache

Section Details Here

== Snapshot the Configuration 

Preserving a functional state of the machine is important in case changes are made accidently. This can be done using VMWare’s snapshot functionality or other software packages for hardware labs.

== Security Services

[Security Services Here]

== Troubleshooting

* [Troubleshooting Issues and Resolutions Here]

== Contributors
* [Contributors Here]
