:toc: left
= Test Lab Guide: Ubuntu 20.04 LTS - Wazuh Server

== Introduction

This document is designed to be used in tandem with the Unix Test Lab Guide (TLG) for Ubuntu 20.04 LTS. It contains instructions on how to install, configure, and test the Wazuh Manager. This guide will provide the user a step-by-step guide, upon completion of which will allow them to build their skills for use in future labs or activities. All configuration steps should be done on the Application Server system unless otherwise noted.

== Installation of Wazuh Manager

It is recommended that you update your system. You can do this using the command `sudo apt update && sudo apt upgrade -y`

. First, add the GPG key
+
```
curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | sudo apt-key add -
```

. Second, add the Wazuh repository
+
```
echo "deb https://packages.wazuh.com/4.x/apt/ stable main" | sudo tee /etc/apt/sources.list.d/wazuh.list
```

. Install the Wazuh Manager
+
```
sudo apt install wazuh-manager
```

. Start and enable the service
+
```
sudo systemctl daemon-reload
sudo systemctl enable --now wazuh-manager
```

. Check status for the Wazuh Manager and confirm that it's running
```
systemctl status wazuh-manager
```

== Installation of ELK Stack

```
sudo apt install elasticsearch-oss opendistroforelasticsearch
```

. Download the configuration file for `/etc/elasticsearch/elasticsearch.yml`
+
```
sudo curl -so /etc/elasticsearch/elasticsearch.yml https://packages.wazuh.com/resources/4.2/open-distro/elasticsearch/7.x/elasticsearch_all_in_one.yml
```

. Configure the Kibana roles and users the the templates below:
.. This adds the following users to Kibana:
... Wazuh_user - Used for read-only access to the Wazuh Kibana plugin.
... Wazuh_admin - For users who need admin privileges.
.. Two additional roles are also added to gives users appropriate permissions:
... Wazuh_ui_user - provides wazuh_user permissions to read the Wazuh's indicies.
... Wazuh_ui_admin - allows wazuh_admin to perform read/write, management and indexing on wazuh indices.
+
```
sudo curl -so /usr/share/elasticsearch/plugins/opendistro_security/securityconfig/roles.yml https://packages.wazuh.com/resources/4.2/open-distro/elasticsearch/roles/roles.yml

sudo curl -so /usr/share/elasticsearch/plugins/opendistro_security/securityconfig/roles_mapping.yml https://packages.wazuh.com/resources/4.2/open-distro/elasticsearch/roles/roles_mapping.yml

sudo curl -so /usr/share/elasticsearch/plugins/opendistro_security/securityconfig/internal_users.yml https://packages.wazuh.com/resources/4.2/open-distro/elasticsearch/roles/internal_users.yml
```

== Install Certificates

. Remove demo certs
+
```
sudo rm -f /etc/elasticsearch/{esnode-key.pem,esnode.pem,kirk-key.pem,kirk.pem,root-ca.pem}
```

. Download the `wazuh-cert-tool.sh`
+
```
sudo su -
curl -so ~/wazuh-cert-tool.sh https://packages.wazuh.com/resources/4.2/open-distro/tools/certificate-utility/wazuh-cert-tool.sh
curl -so ~/instances.yml https://packages.wazuh.com/resources/4.2/open-distro/tools/certificate-utility/instances_aio.yml
```

. Run the `wazuh-cert-tool.sh`
+
```
bash ~/wazuh-cert-tool.sh
```

. Move the Elasticsearch certificates to the correct location
+
```
mkdir /etc/elasticsearch/certs/
mv ~/certs/elasticsearch* /etc/elasticsearch/certs/
mv ~/certs/admin* /etc/elasticsearch/certs/
cp ~/certs/root-ca* /etc/elasticsearch/certs/
```

. Fix the Log4j2 Vulnerability
```
mkdir -p /etc/elasticsearch/jvm.options.d
echo '-Dlog4j2.formatMsgNoLookups=true' > /etc/elasticsearch/jvm.options.d/disabledlog4j.options
chmod 2750 /etc/elasticsearch/jvm.options.d/disabledlog4j.options
chown root:elasticsearch /etc/elasticsearch/jvm.options.d/disabledlog4j.options
```

. Enable and Start Elasticsearch
+
```
systemctl daemon-reload
systemctl enable elasticsearch
systemctl start elasticsearch
systemctl status elasticsearch
```

